services:
  - type: web
    name: huggingface-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: HF_TOKEN
        sync: false
